### ISSUE TITLE
(PC Java 1.16.5 Forge 1.0c custom modpack) incompatible with several other mods that add tameable creatures

### ISSUE THREAD

**Issue by NotYourLifeline** [JayZX535/soulbound-mc#2]
modlist: https://mclo.gs/BvidpYQ

I haven't tried it with all of them yet, but the It gives me the text **It seems you can't forge enough bond with this creature** (don't remember the exact line) when I'm trying to use a Charm of Kinship on certain Mobs.

example:
Enderminion from The Farlanders
Silver Fox from Mystical World

I'm assuming this mod only works on Vanilla mobs, but It'd be nice to get a compatibility patch.

**Comment by JayZX535** [comment]
Hey there, while not all modded mobs are supported _by default_, I suggest taking a look at Soulbound's json configs, as there's a high likelihood that you will be able to add an entry for them manually!  I took a brief peek at their source code and it does look like both of them are considered tamable entities, so it should be possible to set up configuration for them (the other exception would be horses and the like, as they don't have an _owner_ and thus cannot be soulbound).

I didn't realize I never properly got around to documentation for this mod, my apologies haha.  It's currently undergoing a total overhaul for its 1.18 port, that will eventually be transferred back to 1.16 too, and I should have more extensive documentation alongside that version-- and a hopefully more intuitive interface too.

**Comment by NotYourLifeline** [comment]
thank you for the reply! I found the config file you mentioned.
looks like the file already has some modded tamable mobs from Ice and Fire.

though, I understand the 'soulbind cost' and 'resurrection cost' part, but what exactly is the 'gui render scale'? they all seem to have different value, is this supposed to be some kind of HUD size scale?

I mean, I _could_ try different numbers manually... but I'd rather not intentionally kill my pet over and over again just to experiment :')

**Comment by NotYourLifeline** [comment]
},
  "iceandfire:lightning_dragon": {
    "soulbindcost": 64,
    "resurrectioncost": 64,
    "guirenderscale": 1,
    "enforcedbooleans": {
      "NoAI": false,
      "ModelDead": false
    },
    "enforcedintegers": {
      "DeathStage": 0
    }
  },
  "farlanders:enderminion": {
    "soulbindcost": 1,
    "resurrectioncost": 2,
    "guirenderscale": 48
  },
  "mysticalworld:silver_fox": {
    "soulbindcost": 2,
    "resurrectioncost": 4,
    "guirenderscale": 40
  },
}

I added those two in the end but the items still don't seem to be working in-game for some reason :')

**Comment by JayZX535** [comment]
Looks like you've got an extra comma on the silver fox entry, it should just be
```
"mysticalworld:silver_fox": {
"soulbindcost": 2,
"resurrectioncost": 4,
"guirenderscale": 40
}
```
The last item can't have a comma or it breaks the json.

The GUI render scale affects how big the entity renders in the soulbinding GUI.  Since entities aren't all the same dimensions, some of them are too big (hence why dragons in particular are set to a tiny scale haha).  If the fox is similar sized to a wolf, I recommend finding the wolf's setting and reusing that.  The enderminion might need to be a bit smaller if it is tall like an enderman.

**Comment by NotYourLifeline** [comment]
Enderminions are pretty small, actually. 
they're about the same height as the player, but just levitating from the ground a little. like a Blaze.

but I guess they're still much bigger than cats or wolves... so maybe about 20? just like a Cockatrice.

**Comment by NotYourLifeline** [comment]
It worked! and the render scale is just perfect too.

https://ibb.co/mq20nJP

thank you so much for help <3 I love your mod!

**Comment by JayZX535** [comment]
Awesome, thank you!  Glad you were able to get it working, and happy to help!  Since the issue appears to be resolved, I'll go ahead and close this now :)
